name: Docs CI
on:
  push:
    branches: [main]
    paths:
    - 'docs/**'
    - '!docs/**/*.md'
  pull_request:
    branches: [main]
    paths:
    - 'docs/**'
    - '!docs/**/*.md'

jobs:
  docs_ci:
    name: Verify Files
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - name: Install Docs Packages
      working-directory: docs
      run: npm install
    - name: Stylelint Docs
      working-directory: docs
      run: npm run lint:scss
    - name: Install Packages
      run: npm install
    - name: Lint Docs JS Files
      run: node Makefile lintDocsJS

