name: Update Test Ecosystem Plugins

on:
    schedule:
        # “At 00:00 on Monday.” https://crontab.guru/#0_0_*_*_1
        - cron: "0 0 * * 1"
    workflow_dispatch: ~

permissions: read-all

jobs:
    test_ecosystem:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v5
            - uses: actions/setup-node@v6
              with:
                  node-version: "lts/*"
            - run: npm install
            - run: npm run test:ecosystem:update
            - uses: peter-evans/create-pull-request@v7.0.8
              with:
                  commit-message: "chore: update ecosystem plugins"
                  title: "chore: update ecosystem plugins"
